name: Secret Scanning

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  scan-secrets:
    name: Scan for Secrets
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install detect-secrets
        run: pip install detect-secrets

      - name: Scan with detect-secrets
        run: |
          if [[ -f ".secrets.baseline" ]]; then
            detect-secrets scan --baseline .secrets.baseline --all-files
          else
            detect-secrets scan --all-files
          fi

      - name: Scan with trufflehog
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --only-verified

      - name: Install validation dependencies
        run: |
          pip install -r requirements.txt

      - name: Validate secrets manager usage
        run: |
          python scripts/validate_secrets_security.py --check-usage
        continue-on-error: true

      - name: Validate S3 Public Access
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}
        run: |
          python scripts/validate_s3_public_access.py --fail-on-public
        continue-on-error: false

      - name: Comment PR with results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Security scanning completed. No secrets or public S3 access detected!'
            })
