AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Infrastructure for: Shadow Deployment

  Recommendation ID: ml_systems_7
  Priority: NICE_TO_HAVE
  Generated: 2025-10-15T21:01:26.117087

  Description:
  From ML Systems book: Ch 7

  Expected Impact: LOW - Risk-free testing

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name

  ProjectName:
    Type: String
    Default: nba-simulator
    Description: Project name for resource naming

  # TODO: Add specific parameters
  # TODO: Add parameters

Mappings:
  EnvironmentConfig:
    dev:
      InstanceType: t3.small
      MinSize: 1
      MaxSize: 2
    staging:
      InstanceType: t3.medium
      MinSize: 2
      MaxSize: 4
    prod:
      InstanceType: t3.large
      MinSize: 3
      MaxSize: 10

Resources:
  # TODO: Add resources
  # TODO: Add resources

  # Example: S3 Bucket
  # DataBucket:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     BucketName: !Sub '${ProjectName}-${Environment}-shadow_deployment'
  #     VersioningConfiguration:
  #       Status: Enabled
  #     LifecycleConfiguration:
  #       Rules:
  #         - Id: DeleteOldVersions
  #           Status: Enabled
  #           NoncurrentVersionExpirationInDays: 30
  #     Tags:
  #       - Key: Environment
  #         Value: !Ref Environment
  #       - Key: Project
  #         Value: !Ref ProjectName
  #       - Key: RecommendationId
  #         Value: ml_systems_7

  # Example: Lambda Function
  # ProcessingFunction:
  #   Type: AWS::Lambda::Function
  #   Properties:
  #     FunctionName: !Sub '${ProjectName}-${Environment}-shadow_deployment'
  #     Runtime: python3.11
  #     Handler: index.handler
  #     Role: !GetAtt LambdaExecutionRole.Arn
  #     Code:
  #       ZipFile: |
  #         def handler(event, context):
  #             # TODO: Implement function logic
  #             return {'statusCode': 200}
  #     Environment:
  #       Variables:
  #         ENVIRONMENT: !Ref Environment
  #     Tags:
  #       - Key: Environment
  #         Value: !Ref Environment
  #       - Key: RecommendationId
  #         Value: ml_systems_7

  # Example: IAM Role
  # LambdaExecutionRole:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     AssumeRolePolicyDocument:
  #       Version: '2012-10-17'
  #       Statement:
  #         - Effect: Allow
  #           Principal:
  #             Service: lambda.amazonaws.com
  #           Action: sts:AssumeRole
  #     ManagedPolicyArns:
  #       - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  #     Policies:
  #       - PolicyName: ShadowDeploymentPolicy
  #         PolicyDocument:
  #           Version: '2012-10-17'
  #           Statement:
  #             - Effect: Allow
  #               Action:
  #                 - s3:GetObject
  #                 - s3:PutObject
  #               Resource: !Sub '${DataBucket.Arn}/*'

Outputs:
  # TODO: Add outputs
  # TODO: Add outputs

  # Example outputs:
  # BucketName:
  #   Description: Name of the S3 bucket
  #   Value: !Ref DataBucket
  #   Export:
  #     Name: !Sub '${AWS::StackName}-BucketName'
  #
  # FunctionArn:
  #   Description: ARN of the Lambda function
  #   Value: !GetAtt ProcessingFunction.Arn
  #   Export:
  #     Name: !Sub '${AWS::StackName}-FunctionArn'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Environment Configuration
        Parameters:
          - Environment
          - ProjectName
    ParameterLabels:
      Environment:
        default: Deployment Environment
      ProjectName:
        default: Project Name




